spring.application.name=Consumer
server.port=8081

#Kafka - configurations
#Consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.consumer.Consumer.MatchCommentDTOs,com.football.football.DomainLayer.DTO.MatchCommentDTOs
spring.kafka.consumer.properties.spring.json.type.mapping=com.football.football.DomainLayer.DTO.MatchCommentDTOs.MatchCommentDTO:com.consumer.Consumer.MatchCommentDTOs.MatchCommentDTO


