spring.application.name=Consumer
server.port=8081

#Kafka - configurations
#Consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group-1
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=com.consumer.Consumer.asyncMessagingLayer.CustomJsonDeserializer

#Couchbase - configurations
spring.couchbase.bootstrap-host=127.0.0.1
spring.data.couchbase.auto-index=true
spring.couchbase.username=Administrator
spring.couchbase.password=Administrator
spring.couchbase.connection-string=couchbase://localhost
spring.data.couchbase.bucket-name=football.manager.userMatchComments

# Logging configuration for debugging
logging.level.com.consumer.Consumer.asyncMessagingLayer=DEBUG
logging.level.org.springframework.kafka=DEBUG
